config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'

  get'about' => 'pages#about'

  get'amazonsuccess' => 'pages#amazonsuccess'

  get'blog' => 'pages#blog'
 
  get'blogpost1' => 'pages#blogpost1'

  get'calculator' => 'pages#calculator'

  get'calculatorsummary' => 'pages#calculatorsummary'

  get'enterprise' => 'pages#enterprise'
 
  get'learningcenter' => 'pages#learningcenter'

  get'myimaximize' => 'pages#myimaximize'

  get'personalsupport' => 'pages#personalsupport'
 
  get'privacypolicy' => 'pages#privacypolicy'

  get'professional' => 'pages#professional'
 
  get'professionaldashboard' => 'pages#professionaldashboard'

  get'professionalpricing' => 'pages#professionalpricing'
 
  get'termsandconditions' => 'pages#termsandconditions'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def about
   end

  def amazonsuccess
    end

  def blog
  	end

  def blogpost1
  	end

  def calculator
    end

  def calculatorsummary
    end

  def enterprise
  	end

  def home
  	end

  def learningcenter
  	end

  def myimaximize
    end

  def personalsupport
  	end

  def privacypolicy
  	end

  def perfessional
  	end

  def professionaldashboard
  	end

  def professionalpricing
  	end
  	
  def termsandconditions
  	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/views/pages/professional_helper.rb
module Views::Pages::ProfessionalHelper
end

app/views/layouts/_customerpricinggrid.html.erb
<section class="container-fluid" id="section5">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="container">
    <div class="row">
      <div class="col-sm-4 col-xs-12">
            <div class="list-group">
              <a href="#" class="list-group-item active">
                <h2 class="list-group-item-heading">Basic</h2>
                <h6>Free to get started</h6>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Option 100 - more about this</p>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Option 2 - this is more about this</p>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Option 3 GB</p>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Option 4</p>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Feature</p>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Feature</p>
              </a>
              <a href="#" class="list-group-item">
                <button class="btn btn-primary btn-lg btn-block">Get Started</button>
              </a>
            </div>
      </div><!--/left-->
      
      <div class="col-sm-4 col-xs-12">
            <div class="list-group text-center">
              <a href="#" class="list-group-item active">
                <h2 class="list-group-item-heading">Better</h2>
                <h6>Most popular plan</h6>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Option 200 - more about this</p>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Option 2 - this is more about this</p>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Option 5 GB</p>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Option 6</p>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Feature</p>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Feature</p>
              </a>
              <a href="#" class="list-group-item">
                <button class="btn btn-default btn-lg btn-block">$10 per month</button>
              </a>
            </div>
      </div><!--/middle-->
      
      <div class="col-sm-4 col-xs-12">
            <div class="list-group text-right">
              <a href="#" class="list-group-item active">
                <h2 class="list-group-item-heading">Best</h2>
                <h6>For enterprise grade</h6>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Option 100 - more about this</p>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Option 2 - this is more about this</p>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Option 8 GB</p>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Option 10</p>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Unlimited</p>
              </a>
              <a href="#" class="list-group-item">
                <p class="list-group-item-text">Unlimited</p>
              </a>
              <a href="#" class="list-group-item">
                <button class="btn btn-default btn-lg btn-block">$20 per month</button>
              </a>
            </div>
      </div><!--/right-->
      
    </div><!--/row-->
    </div><!--/container--> 
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="row">    
      <div class="col-xs-6 col-sm-6 col-md-3 column">          
          <h4>Information</h4>
          <ul class="nav">
            <li><a href="about-us.html">Products</a></li>
            <li><a href="about-us.html">Services</a></li>
            <li><a href="about-us.html">Benefits</a></li>
            <li><a href="elements.html">Developers</a></li>
          </ul> 
        </div>
      <div class="col-xs-6 col-md-3 column">          
          <h4>Follow Us</h4>
          <ul class="nav">
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Google+</a></li>
            <li><a href="#">Pinterest</a></li>
          </ul> 
      </div>
      <div class="col-xs-6 col-md-3 column">          
          <h4>Contact Us</h4>
          <ul class="nav">
            <li><a href="#">Email</a></li>
            <li><a href="#">Headquarters</a></li>
            <li><a href="#">Management</a></li>
            <li><a href="#">Support</a></li>
          </ul> 
      </div>
      <div class="col-xs-6 col-md-3 column">          
          <h4>Customer Service</h4>
          <ul class="nav">
            <li><a href="#">About Us</a></li>
            <li><a href="#">Delivery Information</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Terms &amp; Conditions</a></li>
          </ul> 
      </div>
    </div><!--/row-->
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="header">
<div class="navbar navbar-default" role="navigation">
<div class="container">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="brand" href="<%= root_path %>">
<img src="<%= asset_path("iMax-Logo.png") %>" width="170" height="48" alt="optional logo">
</a>
</div>
<div class="collapse navbar-collapse navbar-responsive-collapse">
<ul class="nav navbar-nav navbar-left">
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false">Personal <i class="fa fa-angle-down"></i></a>
<ul class="dropdown-menu">
<li><%= link_to "Calculator", calculator_path %></li>
<li><%= link_to "Support", personalsupport_path %></li>
</ul>
</li>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false">Business
<i class="fa fa-angle-down"></i></a>
<ul class="dropdown-menu">
<li><%= link_to "Institution", enterprise_path %></li>
<li><%= link_to "Professional", professional_path %></li>
</ul>
</li>
<li><%= link_to "Learning Center", learningcenter_path %></li>
<li><%= link_to "Get Help", about_path %></li>
</ul>
<ul class="nav pull-right"><li><button type="button" class="btn btn-default navbar-btn">Returning User</button></li>
</ul>
</div>

</div><!-- /navbar-collapse -->
</div>
</div>
<!--/header-->
</nav>

app/views/layouts/_shims.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_zensupport.html.erb
(function() {

  'use strict';

  return {

    resources: {
      TICKET_URL_PATTERN       : /(.+)\.json$/,
      TO_REPLACE_PATTERN       : /\/api\/v2\//,
      REPLACE_BY               : '/agent/#/',
      VAL_MIN                  : 0,
      VAL_MAX                  : 100,
      TIME_OUT                 : 5000,
      TIME_INTERVAL            : 500,
      DEFAULT_PAGE_NUM         : 1,
      FIRST_PAGE               : 1,
      NUM_OF_PAGE_BUTTONS_SHOW : 5,
      TICKET_LINK_HEIGHT       : 26,
      SORT_BY                  : 'created_at',
      SORT_ORDER               : 'asc',
      PAGE_NUM_CLASS           : 'page_number',
      PREV_CLASS               : 'prev',
      NEXT_CLASS               : 'next',
      MODAL_CLASS              : 'my_modal',
      HIDE_CLASS               : 'hidden'
    },

    requests: {
      search: function(searchUrl) {
        return {
          url: searchUrl,
          type: 'GET',
          dataType: 'json'
        };
      }
    },

    events: {
      'app.activated'      : 'init',
      'ticket.save'        : 'saveHookHandler',
      'ticket.submit.done' : 'ticketSubmitDoneHandler',
      'hidden .my_modal'   : 'modalIsHiddenHandler',
      'search.done'        : 'renderTicketLinks',
      'click .prev'        : 'previousTicketsPage',
      'click .next'        : 'nextTicketsPage',
      'click .page_number' : 'searchTicketsByPageNumber'
    },

    init: function() {
      this.pageNumber = this.previousPageNumber = this.resources.DEFAULT_PAGE_NUM;
      this.incrementValue = this.incrementValue || Math.floor(this.resources.VAL_MAX / ( this.resources.TIME_OUT / this.resources.TIME_INTERVAL ));
      this.numOfPageBtnEachSide = this.numOfPageBtnEachSide || Math.floor(this.resources.NUM_OF_PAGE_BUTTONS_SHOW / 2);
      this.ticketsPerPage = this.setting('results_per_page');
      this.sendSearchRequest(this.makeSearchUrl(this.pageNumber)); // Get tickets info on the first page
    },

    previousTicketsPage: function(event) {
      event.preventDefault();
      if (this.pageNumber > this.resources.FIRST_PAGE) {
        this.previousPageNumber = this.pageNumber;
        this.pageNumber--;
        this.sendSearchRequest(this.previousPageQueryUrl); // Get tickets info from previous page.
      }
    },

    nextTicketsPage: function(event) {
      event.preventDefault();
      if (this.pageNumber !== this.totalPages) {
        this.previousPageNumber = this.pageNumber;
        this.pageNumber++;
        this.sendSearchRequest(this.nextPageQueryUrl); // Get tickets info from next page.
      }
    },

    searchTicketsByPageNumber: function(event) {
      event.preventDefault();
      this.previousPageNumber = this.pageNumber;
      this.pageNumber = parseInt(event.currentTarget.text, 10);
      if (this.previousPageNumber !== this.pageNumber) {
        this.sendSearchRequest(this.makeSearchUrl(this.pageNumber)); // Get tickets info given a page number
      }
    },

    renderTicketLinks: function(data) { // Reload App page once ajax call is done.
      this.totalPages = Math.ceil(data.count / this.ticketsPerPage); // Calculate total number of pages.
      this.switchTo('ticket_list', {
        ticketsInfo: data.results,
        pages: _.range(1, this.totalPages + 1),
        total: data.count
      });
      if (data.previous_page === null) {
        this.highlightCurrentPageNumber(this.resources.PREV_CLASS, 0);
      } else {
        this.previousPageQueryUrl = data.previous_page;
        this.removeHighlightOnPageNumber(this.resources.PREV_CLASS, 0);
      }
      if (data.next_page === null) {
        this.highlightCurrentPageNumber(this.resources.NEXT_CLASS, 0);
      } else {
        this.nextPageQueryUrl = data.next_page;
        this.removeHighlightOnPageNumber(this.resources.NEXT_CLASS, 0);
      }

      if (data.count === 0) { // Hide prev and next buttons if there is no ticket
        this.$(this.makeClassSelector(this.resources.PREV_CLASS)).addClass(this.resources.HIDE_CLASS);
        this.$(this.makeClassSelector(this.resources.NEXT_CLASS)).addClass(this.resources.HIDE_CLASS);
      } else { // Otherwise, assign the height of the ticket list body
        this.$('.tickets_list_body').height(this.ticketsPerPage * this.resources.TICKET_LINK_HEIGHT);
      }

      this.removeOrAddHighlight();
      if (this.totalPages > 5) {
        this.reorderPageButtons();
      }
    },

    ticketSubmitDoneHandler: function() { // This is called once ticket.submit.done event is fired.
      clearInterval(this.progress);
      this.toggleModal(this.resources.MODAL_CLASS, false);
    },

    saveHookHandler: function() { // This is called once ticket.save is fired.
      this.switchTo('modal');
      this.commentBody = this.comment().text();
      this.toggleModal(this.resources.MODAL_CLASS, true);
      if (this.commentBody === '') {
        this.showWarningDialog();
        return false;
      } else {
        return this.promise(function(done, fail) {
          this.showSubmitProgressBar();
          this.$progressBar = this.$('.bar'); // Use $ to indicate that the variable is an jQuery object.
          this.currentTime = Date.now();
          this.valNow = this.resources.VAL_MIN;
          this.progress = setInterval(function() {
            this.goProgress(this.valNow);
            if (Date.now() - this.currentTime > this.resources.TIME_OUT) {
              done();
            }
          }.bind(this), this.resources.TIME_INTERVAL);
        });
      }
    },

    modalIsHiddenHandler: function() {
      this.sendSearchRequest(this.makeSearchUrl(this.pageNumber)); // Get tickets info on the first page
    },

    /* Helpers Go Here. */
    toggleModal: function(modalClass, showModal) { // Toggle modal
      var classSelector = this.makeClassSelector(modalClass),
          modalParam;
      if (showModal) {
        modalParam = { backdrop: true, keyboard: false };
      } else {
        modalParam = 'hide';
      }
      this.$(classSelector).modal(modalParam);
    },

    goProgress: function(valNow) { // Bootstrap 2.3 progress bar
      this.valNow += this.incrementValue;
      var percentage = valNow * 100 / this.resources.VAL_MAX;
      this.$progressBar.width(percentage + '%');
      this.$('.sr-only').text(this.I18n.t('progress_percentage', {
        percentage: percentage
      }));
    },

    renderModalLabel: function(label) {
      this.$('.my_modal_label').text(this.I18n.t(label));
    },

    showWarningDialog: function() {
      this.renderModalLabel('modal_header_reject');
      this.toggleModalElementHidden(false);
    },

    showSubmitProgressBar: function() {
      this.renderModalLabel('modal_header_submit');
      this.toggleModalElementHidden(true);
    },

    toggleModalElementHidden: function(isProgressBarOnShown) {
      this.$('.alert-block, .modal-footer').toggleClass(this.resources.HIDE_CLASS, isProgressBarOnShown);
      this.$('.progress').toggleClass(this.resources.HIDE_CLASS, !isProgressBarOnShown);
    },

    makeSearchUrl: function(pageNumber) { // This search query searches for all open tickets that are assigned to the current user.
      var query = helpers.fmt('assignee:%@+type:ticket+status:open', this.currentUser().email());
      return helpers.fmt('/api/v2/search.json?page=%@&per_page=%@&query=%@&sort_by=%@&sort_order=%@', pageNumber, this.ticketsPerPage, query, this.resources.SORT_BY, this.resources.SORT_ORDER);
    },

    sendSearchRequest: function(queryUrl) {
      this.switchTo('loading_screen');
      this.ajax('search', queryUrl); // Fire jQuery-like ajax request
    },

    getHighlightPaginationButton: function(btnClass, index) { // Return a jQuery object of the page button to be highlighted
      index = index || 0;
      return this.$(this.makeClassSelector(btnClass)).eq(index).parent();
    },

    highlightCurrentPageNumber: function(btnClass, index) {
      this.getHighlightPaginationButton(btnClass, index)
        .addClass('active');
      console.log('add');
    },

    removeHighlightOnPageNumber: function(btnClass, index) {
      this.getHighlightPaginationButton(btnClass, index)
          .removeClass('active');
      console.log('remove');
    },

    removeOrAddHighlight: function() {
      if (this.previousPageNumber !== this.pageNumber) { // Remove highlight on previously selected page.
        this.removeHighlightOnPageNumber(this.resources.PAGE_NUM_CLASS, this.previousPageNumber - 1);
      }
      this.highlightCurrentPageNumber(this.resources.PAGE_NUM_CLASS, this.pageNumber - 1);
    },

    reorderPageButtons: function() { // Always have at most 7 buttons displayed (2 for nav, 5 for page numbers)
      this.$('.pagi').addClass(this.resources.HIDE_CLASS);
      var extraBelow = this.numOfPageBtnEachSide - (this.totalPages - this.pageNumber), // if we are close to the end, show more pages lower than this.pageNumber
          extraAbove = this.numOfPageBtnEachSide - (this.pageNumber - this.resources.DEFAULT_PAGE_NUM); // if we are close to the start, show more pages greater than this.pageNumber
      extraBelow = (extraBelow > 0) ? extraBelow : 0; // if you're at the last page (9) show extra pages below it (8,7,6,5)
      extraAbove = (extraAbove > 0) ? extraAbove : 0; // if at page 1 show not just 2, 3 but also 4 and 5
      for (var i = this.pageNumber - this.numOfPageBtnEachSide - extraBelow; i <= this.pageNumber + this.numOfPageBtnEachSide + extraAbove; i++) {
        this.$('.' + this.makePagiClassName(i)).removeClass(this.resources.HIDE_CLASS);
      }
    },

    makePagiClassName: function(pageNumber) {
      return 'pagi' + pageNumber;
    },

    makeClassSelector: function(className) {
      return '.' + className;
    }
  };

}());

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Imaximize</title>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
 <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
<%= render 'layouts/header' %>
<div class="container-fluid">
<%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
    	<div class="loader">
    		<div class="spinner">
			  <div class="double-bounce1"></div>
			  <div class="double-bounce2"></div>
			</div>
    	</div>
				
		<div class="nav-container">
		</div>
		
		<div class="main-container">
		<section class="pure-text-centered">
				<div class="container">
					<div class="row">
						<div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 text-center">
							<span class="sub alt-font"> </span>
							<h1><strong>This heading requires a little emphasis</strong></h1>
							<p class="lead">
								At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.
							</p>
						</div>
					</div>
		
				</div>
			</section>
			
			<section class="team-1">
				<div class="container">
					<div class="row">
						<div class="col-md-8 col-md-offset-2 text-center">
							<h1>About Our Team</h1>
						</div>
					</div>
					
					<div class="row space-bottom-large">
						<div class="col-sm-4">
							<div class="team-1-member">
								<img alt="Team Member" src="img/team-small-1.png ">
								<h2>Wesley Joiner, CWS</h2>
								<h5>President and Founder</h5>
								<p class="space-top-small">
									Founder of iMaximize Social Security. Leads management team and coordinates operational leadership. Institutional client relationship manager. Prior experience in banking and investment management.</p>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="team-1-member">
								<img alt="Team Member" src="img/team-small-3.png ">
								<h2>William Joiner, CWS</h2>
								<h5>CFO</h5>
								<p class="space-top-small">Co-Founder of iMaximize Social Security. Mr.Joiner brings over 20 years of experience in the independent advisory space. William provides leadership to iMaximize Advisory service team and assist in the coordination of strategic objectives.</p>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="team-1-member">
								<img alt="Team Member" src="img/team-small-5.png ">
								<h2>Frank Mann, CPA, MAcc</h2>
								<h5>CPA</h5>
								<p class="space-top-small">
									Frank servs as iMaximize CFO. Mr. Mann has prior experience in Audit Accounting for Fortune 400 firms and provides financial leadership to iMaximize. Mr.Mann has specific experience in company valuation and pricing.</p>
							</div>
						</div>
						
		
					</div>
					
					
					
				</div>
			</section>
			
			<section class="team-1">
				<div class="container">
					
					
					<div class="row space-bottom-large">
						<div class="col-sm-4">
							<div class="team-1-member">
								<img alt="Team Member" src="img/team-small-1.png ">
								<h2>Mary Ellyse Fendig</h2>
								<h5>Executive Assistant</h5>
								<p class="space-top-small">
									Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
								</p>
							</div>
						</div>
						
						
						
						
						
		
					</div>
					
					
					
				</div>
			</section>
			
			<section>
				<div class="container">
					<div class="row">
						<div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 text-center">
							<i class="icon icon-jumbo social_twitter"></i>
							<div id="tweets" data-widget-id="492085717044981760">
							
							</div>
							<p>
								Follow us <strong><a href="#">@i</a>maxsocsec</strong> for more awesome updates
							</p>
						</div>
					</div>
				</div>
			</section>
		</div>
		
		<div class="footer-container">

app/views/pages/amazonsuccess.html.erb
<html>
<head>
	<script src="http://imaximizesocialsecurity.com/wp-includes/js/jquery/jquery.js"></script>
	<script src="/wp-content/themes/imaximize/js/angular-app/amplify.store.js"></script>
	<script type="text/javascript">
		var $ = jQuery.noConflict();

		var PurchaseJS=
		{
			Init:function()
			{
				var authToken = amplify.store( "authToken" );

				if( !authToken )
				{
					window.location = "/individual/calculator";
					return;
				}

				var baseUri = "http://api.imaximizesocialsecurity.com/api/";

				 $.ajax(baseUri + "AmazonPayment",
		        {
		            type: "GET",
		            headers: { "TC_ApiAuthToken": authToken },

		            success: function (results)
		            {
		            	amplify.store("showReport", "1");

		                window.location = "/individual/calculator/?page_id=134&sr=1";
		            },

		            error: function (jqXhr)
		            {
		            	window.location = "/individual/calculator";  
		            }
		        });
			}
		};

		$(document).ready( PurchaseJS.Init );
	</script>
</head>
<body>
	Thank you for your purchase, redirecting...
</body>
</html>

app/views/pages/calculator.html.erb
<H1>This is the calculator page</h1>
	

app/views/pages/learningcenter.html.erb
<h1>Pages#learningcenter</h1>
<p>Find me in app/views/pages/learningcenter.html.erb</p>